### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Felix0301** [litecoin-project/p2sh-convert#13]
Thank you for the great tool!
Is there any documentation available on how the conversion works, s.t. one could do their own implementation?

Thanks in advance

**Comment by Veezywqp1** [comment]
> Thank you for the great tool! Is there any documentation available on how the conversion works, s.t. one could do their own implementation?
> 
> Thanks in advance

**Comment by losh11** [comment]
You should not be using this tool. This exists for Litecoin developers only.
