### ISSUE TITLE
Block explorers that support new format

### ISSUE THREAD

**Issue by jflowers1974** [litecoin-project/p2sh-convert#2]
Forgive me, I just ran across this and had to step away from my computer today. But before I do... I was wondering if there's a master list of blockchain explorers that support the new address(es).  I was testing the code and resulting addresses on (chain.so, and a couple of others)...  only they weren't able to recognize the resulting pattern. Thanks in advance.

**Comment by losh11** [comment]
insight.litecore.io supports the new P2SH addresses. There are a few
issues, but I'm hoping to solve that soon.
