### ISSUE TITLE
Don't use placeholder

### ISSUE THREAD

**Issue by prusnak** [litecoin-project/p2sh-convert#6]
Revert commit https://github.com/litecoin-project/p2sh-convert/commit/9dbbd1f630c3c27cfd89e33d5f6629320077b113

There are still some people that somehow manage to unintentionally send coins to this address, even though the address could not be copied.

**Comment by losh11** [comment]
Addressed in 268f1e6

I'm genuinely interested in how these people somehow manage to send coins to a placeholder address.

**Comment by prusnak** [comment]
They copy the address via typing it letter by letter to make it
"more secure".
