### ISSUE TITLE
API for programatic access?

### ISSUE THREAD

**Issue by mecampbellsoup** [litecoin-project/p2sh-convert#8]
i.e. so one can `curl` this service like:

```bash
curl https://api.https://litecoin-project.github.io/p2sh-convert/{address}
```

The response would include the "other" address and which type it is - deprecated or P2SH.

**Comment by losh11** [comment]
Since everyone is asking, I made a nodejs app which does this.
https://github.com/losh11/base58Check-converter-server

At the moment we aren't running such a service, but it shouldn't be too hard for you to do!
